[package]
name = "local_runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
machine_mock = { path = "../machine_mock" }
ctrlc = "3.2.5"
